# Site Settings
remote_theme: chrisrhymes/bulma-clean-theme
lang: en
title: LavWell Technologies
tagline: Turning waste into wellness
email: info@lavwell.com
description: >
  LavWell Technologies is building a new model of preventative wellness management through passive, continous measurement
baseurl: ""
url: "https://www.lavwell.com"
permalink: pretty
favicon: /img/GuardianHealthLogoMark.png
#navbar_icon image must have an aspect ratio of 3-by-1, or the file /includes/header.html needs an update
navbar_icon: /navbar-icon.png
#hide_share_buttons: true
theme_color: '#00827f'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "LavWell Technologies"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
